// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/tasks": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-up" | "/login" | "/dashboard" | "/dashboard/tasks" | "/dashboard/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/tasks" | "/dashboard/settings";
  };
  "routes/dashboard-home.tsx": {
    id: "routes/dashboard-home";
    page: "/dashboard";
  };
  "routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/dashboard/tasks";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/dashboard/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/sign-up": typeof import("./app/routes/sign-up.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard-home": typeof import("./app/routes/dashboard-home.tsx");
  "routes/tasks": typeof import("./app/routes/tasks.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};